package ${packageName}.ui.main;

import dagger.Subcomponent;

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

@ActivityScoped
@Subcomponent(modules = {MainModule.class, ActivityModule.class})
public interface MainComponent {

    void inject(final MainActivity activity);

    @Subcomponent.Builder
    interface Builder {
        Builder mainModule(MainModule module);
        Builder activityModule(ActivityModule module);
        MainComponent build();
    }

    MainContract.Presenter getMainPresenter();
    MainContract.Model getMainModel();

}