package ${packageName}.ui.main;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

public class MainModel implements MainContract.Model {

    public MainModel() {

    }

}