package ${packageName};
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

public interface ${contractName} {

    interface View {

    }

    interface Presenter {
        void start();

        void stop();
    }

}