package ${packageName};

import android.app.Fragment;

/**
 *
 *  Developed by SergioCT
 *
 *  www.SergioCrespoToubes.com
 *  https://github.com/Sergioct
 *
 *  Code autogenerated. 
 *
 */

public class ${fragmentName} extends Fragment {

}