package ${packageName};

/**
 *
 *  Developed by SergioCT
 *
 *  www.SergioCrespoToubes.com
 *  https://github.com/Sergioct
 *
 *  Code autogenerated. 
 *
 */

public class ${presenterName} implements ${contractName}.Presenter {

    @Override
    public void start() {

    }

    @Override
    public void stop() {

    }

}