package ${packageName};
 
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */
  
public class ${modelName}{
    
    private Context mContext;

    @Inject
    public ${modelName}(Context context) {
        this.mContext = context;
    }

}
