package ${packageName}.ui.splash;

import dagger.Subcomponent;

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

@ActivityScoped
@Subcomponent(modules = {SplashModule.class, ActivityModule.class})
public interface SplashComponent {

    void inject(final SplashActivity activity);

    @Subcomponent.Builder
    interface Builder {
        Builder splashModule(SplashModule module);
        Builder activityModule(ActivityModule module);
        SplashComponent build();
    }

    SplashContract.Presenter getSplashPresenter();
    SplashContract.Model getSplashModel();

}