package ${packageName}.ui.splash;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

public interface SplashContract {

    interface View extends BaseContract.View {

    }

    interface Presenter extends BaseContract.Presenter {
        
    }

    interface Model extends BaseContract.Model {
        
    }

}