package ${packageName}.ui.splash;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

public class SplashModel implements SplashContract.Model {

    public SplashModel() {
    }

}