package ${packageName}.ui.splash;
  
import dagger.Module;
import dagger.Provides;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

@Module
public class SplashModule {

    @Provides
    @ActivityScoped
    public SplashContract.Presenter provideSplashPresenter(SplashContract.Model model){
        return new SplashPresenter(model);
    }

    @Provides
    @ActivityScoped
    public SplashContract.Model provideSplashModel(){
        return new SplashModel();
    }

}