package ${packageName}.ui.splash;

import io.reactivex.disposables.CompositeDisposable;

/**
 *
 *  Developed by SergioCT
 *
 *  www.SergioCrespoToubes.com
 *  https://github.com/Sergioct
 *
 *  Code autogenerated. 
 *
 */

public class SplashPresenter implements SplashContract.Presenter {

    private SplashContract.View view;
    private SplashContract.Model model;

    private CompositeDisposable compositeDisposable;

    public SplashPresenter(SplashContract.Model model) {
        this.model = model;
        compositeDisposable = new CompositeDisposable();
    }

    @Override
    public void setView(BaseContract.View view) {
        this.view = (SplashContract.View) view;
    }

    @Override
    public void dropView() {
        compositeDisposable.clear();
    }

}
