package ${packageName};
 
import android.os.Bundle;
import javax.inject.Inject;

/**
 *
 *  Developed by SergioCT
 *
 *  www.SergioCrespoToubes.com
 *  https://github.com/Sergioct
 *
 *  Code autogenerated. 
 *
 */

public class ${activityName} extends BaseActivity {
 
    @Inject
    ${contractName}.Presenter mPresenter;
    
    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.${activityLayoutName});
    }

    @Override
    protected void onStart() {
        super.onStart();
        mPresenter.start();
    }

    @Override
    protected void onStop() {
        super.onStop();
        mPresenter.stop();
    }
    
}