package ${packageName};
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

public class ${appName}Application extends Application {

    public static AppComponent appComponent;

    private ApiControllerRetrofit apiControllerRetrofit;
    private Picasso picasso;
    //public static MyRoomDatabase db;

    public static ${appName}Application get(Activity activity){
        return (${appName}Application)activity.getApplication();
    }

    @Override
    public void onCreate() {
        super.onCreate();

        // Init Jodatime
        JodaTimeAndroid.init(this);

        // Init dagger

        appComponent = DaggerAppComponent.builder()
                .appModule(new AppModule(this))
                //.dbModule(new DbModule(this))
                .networkModule(new NetworkModule("https://jsonplaceholder.typicode.com"))
                .build();

        apiControllerRetrofit = appComponent.getApiControllerRetrofit();
        picasso = appComponent.getPicasso();
        db = appComponent.getMyRoomDatabase();

    }

}