package ${packageName}.ui.main;

import android.app.Activity;

/**
 *
 *  Developed by SergioCT
 *
 *  www.SergioCrespoToubes.com
 *  https://github.com/Sergioct
 *
 *  Code autogenerated. 
 *
 */

public class MainActivity extends AppCompatActivity implements MainContract.View {

// Injects

    @Inject
    MainContract.Presenter presenter;

    @Inject
    Retrofit retrofit;

    @Inject
    Picasso picasso;

    // Views

    // Vars

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);

        MainComponent mainComponent = MyApplication.appComponent.activityComponent().build();
        mainComponent.inject(this);
        presenter.setView(this);
    }

}