package ${packageName}.di.scopes;
  
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import javax.inject.Scope;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

@Scope
@Retention(RetentionPolicy.CLASS)
public @interface ApplicationScoped {
}
