package ${packageName}.di.modules;
  
import android.support.annotation.NonNull;
import android.support.v4.app.Fragment;
import dagger.Module;
import dagger.Provides;

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

@Module
@FragmentScoped
public class FragmentModule {

    private final Fragment mFragment;

    public FragmentModule(@NonNull final Fragment fragment) {
        mFragment = fragment;
    }

    @Provides
    @FragmentScoped
    Fragment provideFragment() {
        return mFragment;
    }

}