package ${packageName}.di.modules;

import dagger.Module;
import dagger.Provides;
import android.app.Activity;
import android.content.Context;
import android.support.annotation.NonNull;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

/**
 * Module providing Activity context per Activity.
 */
@Module
public class ActivityModule {

    private final Activity mActivity;

    public ActivityModule(@NonNull final Activity activity) {
        mActivity = activity;
    }

    @Provides
    @ActivityScoped
    Activity provideActivity() {
        return mActivity;
    }

    @Provides
    @ActivityScoped
    //@Named("activity_context")
    Context provideActivityContext() {
        return mActivity;
    }
}