package ${packageName}.di.modules;
  
import dagger.Module;
import dagger.Provides;
import android.content.Context;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

@Module
public class AppModule {

    private MyApplication myApplication;

    public AppModule(MyApplication pregnancyApplication) {
        this.myApplication = pregnancyApplication;
    }

    @Provides
    @ApplicationScoped
    public MyApplication provideMyApplication() {
    return myApplication;
  }

    @Provides
    @ApplicationScoped
    @ApplicationContext
    public Context provideApplicationContext() {
    return myApplication;
  }

}