package ${packageName}.di.modules;
  
import com.squareup.picasso.Picasso;
import dagger.Module;
import dagger.Provides;

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

@Module(includes = AppModule.class)
public class PicassoModule {

    @Provides
    @ApplicationScoped
    public Picasso providePicasso(@ApplicationContext Context context){
        return new Picasso.Builder(context)
                .build();
    }

}
