package ${packageName}.di.scopes;
  
import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import javax.inject.Scope;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

@Scope
@Documented
@Retention(value = RetentionPolicy.RUNTIME)
public @interface UserScoped {
}