package ${packageName}.network;
  
import java.util.List;

import io.reactivex.Observable;
import io.reactivex.Single;
import retrofit2.http.GET;
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

public interface ApiControllerRetrofit {

    @GET("/posts")
    Single<List<Post>> getPosts();

    @GET("/posts")
    Observable<Post> getPostsObservable();

    //@Headers("Content-Type: application/json")
    //@POST("/posts")
    //String postData(@Body Map<String, Object> body);

}